openapi: 3.0.0
info:
  title: E-Commerce Demo API
  description: API for managing e-commerce demo operations
  version: 1.0.0
servers:
    - url: http://localhost:8080/api/v1
paths:
    /products:
        get:
          summary: Get all products
          operationId: getAllProducts
          tags:
            - Products
          parameters:
            - name: page
              in: query
              description: Page number for pagination
              required: false
              schema:
                type: integer
                default: 1
            - name: size
              in: query
              description: Number of products per page
              required: false
              schema:
                type: integer
                default: 10
          responses:
            '200':
              description: A list of products
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      products:
                        type: array
                        items:
                          $ref: '#/components/schemas/Product'
                      totalPages:
                        type: integer
                      totalElements:
                        type: integer
            '500':
              description: Internal server error
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string